spring:
#  datasource:
#    url: jdbc:mysql://10.1.1.97:3311/batch_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Rtqw123OpnmER

  elasticjob:
    datasource:
      url: jdbc:mysql://10.1.1.97:3311/batch_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Rtqw123OpnmER
    regCenter:
      serverList: 10.1.1.97:2181
      namespace: elasticJobDemo
