spring:
#  datasource:
#    url: jdbc:mysql://10.1.1.97:3311/batch_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Rtqw123OpnmER

  elasticjob:
    datasource:
      url: jdbc:mysql://rm-wz9103hxfjd22t1j2.mysql.rds.aliyuncs.com:3306/elasticjob_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: quixmart
      password: qx#dp0810
    regCenter:
      serverList: 10.107.139.125:2181,10.110.112.195:2181,10.103.118.234:2181
      namespace: elasticJobDemo
    scheduled:
      jobConfigMap:
        myJobConfig:
          jobName: myJob
          cron: 123
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: 1
        youJobConfig:
          jobName: myJob
          cron: 123
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: 1
        PropertiesSimpleJob:
          jobName: PropertiesSimpleJob
          cron: 0 0/1 * * * ?
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: test
