spring:
#  datasource:
#    url: jdbc:mysql://10.1.1.97:3311/batch_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Rtqw123OpnmER

  elasticjob:
    datasource:
      url: jdbc:mysql://10.1.1.97:3311/batch_log?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Rtqw123OpnmER
    regCenter:
      serverList: 10.1.1.97:2181
      namespace: elasticJobDemo
    scheduled:
      jopMap:
        myJobConfig:
          jobName: myJobConfig
          cron: 123
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: 1
        youJobConfig:
          jobName: youJobConfig
          cron: 123
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: 1
        PropertiesSimpleJob:
          jobName: PropertiesSimpleJob
          cron: 0 0/1 * * * ?
          shardingTotalCount: 1
          shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
          jobParameters: test
